# Generated by Django 2.0.7 on 2019-11-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=64, verbose_name='标题')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedate', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('isenable', models.BooleanField(default=True, verbose_name='是否可见')),
            ],
        ),
    ]
