# Generated by Django 2.0.7 on 2019-11-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_article', '0002_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='isenable',
            field=models.BooleanField(choices=[(True, '可见'), (False, '私密')], default=True, verbose_name='是否可见'),
        ),
    ]
