# Generated by Django 2.0.7 on 2019-11-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.TextField(default='', verbose_name='用户头像'),
        ),
    ]
