# Generated by Django 2.0.7 on 2019-11-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tags',
            field=models.TextField(default='[]', verbose_name='标签'),
        ),
    ]
