# Generated by Django 2.0.7 on 2019-11-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_auto_20191127_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='', max_length=64, verbose_name='姓名,并非用户名'),
        ),
    ]
