# Generated by Django 2.0.7 on 2019-11-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0005_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='', max_length=64, verbose_name='手机号码'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram',
            field=models.CharField(default='', max_length=64, verbose_name='Tg'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wechat',
            field=models.CharField(default='', max_length=64, verbose_name='微信'),
        ),
    ]
