# Generated by Django 2.0.7 on 2019-12-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0006_auto_20191130_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloudword', models.TextField(default='', verbose_name='云词图base64')),
            ],
        ),
    ]
