# Generated by Django 2.0.7 on 2019-12-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0007_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='tag',
            field=models.TextField(default='[]', verbose_name='标签'),
        ),
    ]
