# Generated by Django 2.0.7 on 2019-12-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0008_userdata_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='cloudword_width',
            field=models.CharField(default='260', max_length=64, verbose_name='云词图大小'),
        ),
    ]
