# Generated by Django 2.0.7 on 2019-12-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0009_userdata_cloudword_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='timeline',
            field=models.TextField(default='', verbose_name='时光轴内容'),
        ),
    ]
