# Generated by Django 2.0.7 on 2019-07-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.IntegerField(choices=[(0, '超管'), (1, '博主')], default=0, verbose_name='用户角色'),
        ),
    ]
