# Generated by Django 2.0.7 on 2019-08-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='默认标题', max_length=64, verbose_name='标题')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('starttime', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('titleimage', models.ImageField(default='', upload_to='', verbose_name='标题图片')),
                ('contentimage', models.ImageField(default='', upload_to='', verbose_name='内容图片')),
                ('city', models.CharField(default='', max_length=64, verbose_name='定位')),
                ('pageviews', models.IntegerField(default=0, verbose_name='浏览量')),
                ('top', models.BooleanField(default=False, verbose_name='置顶文章')),
                ('secret', models.BooleanField(default=False, verbose_name='私密')),
            ],
            options={
                'db_table': 'article_app_Article',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=16, verbose_name='标签名')),
            ],
            options={
                'db_table': 'article_app_Tag',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(default='', to='article_app.Tag', verbose_name='标签'),
        ),
    ]
