# Generated by Django 2.0.7 on 2019-08-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ui',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='起风了', verbose_name='Ui标题')),
            ],
            options={
                'db_table': 'ui_app_Ui',
            },
        ),
    ]
